version: '3'
services:
  nginx:
    image: tiangolo/nginx-rtmp:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./streams:/hls/live
    ports:
      - "80:80"
      - "1935:1935"
